[workspace]
default-members = ["host-basic"]
# exclude = []
members = ["host-basic", "host-mod", "host-techno", "guest-sin", "guest-mul", "guest-techno"]
resolver = "1"

[workspace.package]
version = "0.1.0"
edition = "2021"