package component:mul;

world audio {
     record param-info {
        name: string,
        min: f32,
        max: f32,
        default: f32,
    }
    export set: func(key: string, value: f32);
    export get-params: func() -> list<param-info>;
    export process: func(input: list<f32>) -> list<f32>;
}
